server:
  port: 8084
  servlet:
    context-path: /api
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:sql/seed_admin.sql
  flyway:
    enabled: false
    encoding: UTF-8
  datasource:
    url: ${LOCAL_DB_URL:jdbc:mysql://localhost:3306/appdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8}
    username: ${LOCAL_DB_USER:root}
    password: ${LOCAL_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8084/api/api/oauth2/login/google}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID:}
            client-secret: ${KAKAO_CLIENT_SECRET:}
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8084/api/api/oauth2/login/kakao}
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:}
        secret-key: ${AWS_SECRET_ACCESS_KEY:}

jwt:
  secret: ${JWT_SECRET_KEY:}
  access-token-expire-time: 1800
  refresh-token-expire-time: 604800

admin:
  code: ${ADMIN_CODE:}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  newrelic:
    metrics:
      export:
        enabled: false
        api-key: ${NEW_RELIC_API_KEY:}
        account-id: ${NEW_RELIC_ACCOUNT_ID:}
        uri: https://insights-collector.newrelic.com
        step: 1m

app:
  s3:
    bucket: ${S3_BUCKET_NAME:}
    urlBase: ${S3_URL_BASE:}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
